name: Spring Boot CI

on:
  push:
    branches: [ "master" ]
 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Run Tests
        run: ./mvnw test

      - name: Build Docker Image
        run: docker build -t springboot-app .







